version: 2
jobs:
  build:
    working_directory: ~/typescript-boilerplate
    docker:
      - image: circleci/node:6-stretch-browsers
    steps:
      - checkout
      - run:
          name: install dep
          command: bash scripts/deps.sh

